### DEVO Config File for MVSEC ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 48
REMOVAL_WINDOW: 15
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 10
BUFFER_SIZE: 4096 # 8192 for outdoor_day2, 4096 otherwise

# PATCHES_PER_FRAME: 96
# REMOVAL_WINDOW: 22
# OPTIMIZATION_WINDOW: 10
# PATCH_LIFETIME: 13
# BUFFER_SIZE: 4096 # 8192 for outdoor_day2, 4096 otherwise

# threshold for keyframe removal
KEYFRAME_THRESH: 15.0 # 5.0 for outdoor_day1

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.7

# maybe use mixed precision for inference
MIXED_PRECISION: True

# Select between random, gradient, scorer
PATCH_SELECTOR: 'scorer'
# Normalizer (only evs): none, rescale, standard (std)
NORM: 'std'
# Eval mode of patch selector (random, topk, multinomial)
SCORER_EVAL_MODE: 'multi'
SCORER_EVAL_USE_GRID: True
